### ISSUE TITLE
Fails on Radeon R5

### ISSUE THREAD

**Issue by tomchiverton** [Ricks-Lab/amdgpu-utils#3]
#lpci | grep VGA
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wani [Radeon R5/R6/R7 Graphics] (rev 84)

#clinfo |grep 'loader Profile'
Device open failed, aborting...
Device open failed, aborting...
Device open failed, aborting...
Device open failed, aborting...
Device open failed, aborting...
  ICD loader Profile                              OpenCL 2.2

and yet

#./amdgpu-ls --clinfo 
Cannot read ppfeaturemask. Exiting...

**Comment by Ricks-Lab** [comment]
Thanks for the details.  Since the end goal of this project is to control AMD GPU's which is only possible when using the latest drivers, all tools in the package had been written to be dependent on the existence of /sys/module/amdgpu/parameters/ppfeaturemask.  The driver must be "amdgpu".  If I execute lshw | grep configuration, I can see the line "configuration: driver=amdgpu latency=0" indicating the driver.  Which driver package are you using?  I will try to do some research to better describe GPU compatibility.

**Comment by Ricks-Lab** [comment]
I have added a check for amdgpu and current driver package version at startup.  Let me know if this correctly identifies your situation.  Also, it looks like there is a version of the amdgpu drivers that is compatible with R5.

**Comment by Ricks-Lab** [comment]
Improved compatibility checks and messaging in v2.0.0.
