### ISSUE TITLE
X-axis values obscured in amdgpu-plot 

### ISSUE THREAD

**Issue by csecht** [Ricks-Lab/amdgpu-utils#34]
The time series graphs for *amdgpu-plot*  show only a small portion of the x-axis values. I'm pretty sure this was an issue prior to the most recent Master.
![amdgpu-plot](https://user-images.githubusercontent.com/47796546/61185353-fd925980-a61d-11e9-8957-4c3a82ac4afd.png)

**Comment by csecht** [comment]
...and local time is shown whether *amdgpu-plot* or *amdgpu-plot --ltz * is used.  Is UTC an option?

**Comment by Ricks-Lab** [comment]
> ...and local time is shown whether _amdgpu-plot_ or _amdgpu-plot --ltz_ is used. Is UTC an option?

It should definitely display in UTC if the *--ltz* option is not specified.  I have just tried this on my system and found that the *--ltz* option is working correctly for both monitor and plot.  Can you send me your command line for when you see the issue?

It is intended that the x-axis labels are not shown.  I just made a change on master that should make this the case now.  Since I have 3 and 5 GPUs on my 2 Linux systems, I can not see the obscured labels that you see with two GPUs.  Please give it a try and let me know the results.

**Comment by csecht** [comment]
Okay, I messed up with the times, sorry. I just confirmed on my system that the default for *-monitor --log* and *-plot* both display UTC and the *--ltz* option for both displays local time. All that I can figure is that yesterday my brain couldn't wrap its neurons around AM vs. PM. vs. 24-hr time. 

Yes,  *-plot* with the new Master displays no values on the X-axes.  Looks good!
![amdgpu-plot](https://user-images.githubusercontent.com/47796546/61239660-0f026100-a705-11e9-9761-4ac4d1e377db.png)

**Comment by Ricks-Lab** [comment]
I plan to make an official release this weekend. Let me know if there is anything else we should try to clean up before then.

**Comment by csecht** [comment]
I can't think of anything. 
After that release, one of the big updates likely needed will be for the new RX 5700 series of cards. Those cards, however, are still waiting for driver updates to be useful for mining or crunching. Once that happens, I might get an RX 5700 for E@H work.
